USE BENHVIENANHBINH
GO

DROP PROC THEM_HOA_DON
CREATE PROC THEM_HOA_DON
	@MA_HD CHAR(5),
	@HINHTHUCTHANHTOAN BIT,
	@NGAYLAP_HD DATE,
	@MA_PDKT CHAR(5),
	@STK CHAR(10),
	@DATHANHTOAN BIT,
	@TONGTIEN FLOAT
AS
BEGIN
	INSERT HOADON VALUES(@MA_HD, @MA_PDKT, @NGAYLAP_HD, @STK, @HINHTHUCTHANHTOAN, @TONGTIEN, @DATHANHTOAN)
END
GO

DROP PROC CAP_NHAP_HOA_DON
CREATE PROC CAP_NHAP_HOA_DON
	@MA_HD CHAR(5),
	@DOTTHANHTOAN INT,
	@SOTIENTHANHTOAN FLOAT,
	@HANTHANHTOAN DATE,
	@DATHANHTOAN BIT
AS
BEGIN
	IF (SELECT TONGTIEN*0.25 FROM HOADON WHERE MA_HD = @MA_HD) > @SOTIENTHANHTOAN
		BEGIN
			RAISERROR (N'Số tiền thanh toán không đủ tối thiểu!', 16, 1)
			RETURN
		END

	IF (@DOTTHANHTOAN > 4)
		BEGIN
			RAISERROR (N'Đợt thanh toán quá mức!', 16, 1)
			RETURN
		END

	UPDATE HOADON
	SET @DATHANHTOAN = @DATHANHTOAN
	WHERE HOADON.MA_HD = @MA_HD

	INSERT CHITIET_HD VALUES(@MA_HD, @DOTTHANHTOAN, @SOTIENTHANHTOAN, @HANTHANHTOAN, @DATHANHTOAN) 
END
GO

