USE BENHVIENANHBINH
GO

DROP PROC THANH_TOAN_1_LAN
CREATE PROC THANH_TOAN_1_LAN
	@MA_HD CHAR(5),
	@NGAYLAP_HD DATE,
	@MA_PDKT CHAR(5),
	@STK CHAR(10),
	@DATHANHTOAN BIT,
	@TONGTIEN FLOAT
AS
BEGIN
	INSERT HOADON VALUES(@MA_HD, @MA_PDKT, @NGAYLAP_HD, @STK, 0, @TONGTIEN, @DATHANHTOAN)
END
GO

DROP PROC THANH_TOAN_THEO_DOT
CREATE PROC THANH_TOAN_THEO_DOT
	@MA_HD CHAR(5),
	@NGAYLAP_HD DATE,
	@MA_PDKT CHAR(5),
	@STK CHAR(10),
	@TONGTIEN FLOAT
AS
BEGIN
	INSERT HOADON VALUES(@MA_HD, @MA_PDKT, @NGAYLAP_HD, @STK, 1, @TONGTIEN, 0)
	INSERT CHITIET_HD VALUES(@MA_HD, 1, @TONGTIEN*0.25, @NGAYLAP_HD, 1)
	INSERT CHITIET_HD VALUES(@MA_HD, 2, @TONGTIEN*0.25, @NGAYLAP_HD, 0)
	INSERT CHITIET_HD VALUES(@MA_HD, 3, @TONGTIEN*0.25, @NGAYLAP_HD, 0)
	INSERT CHITIET_HD VALUES(@MA_HD, 4, @TONGTIEN*0.25, @NGAYLAP_HD, 0)
END
GO

DROP PROC CAP_NHAP_HOA_DON
CREATE PROC CAP_NHAP_HOA_DON
	@MA_HD CHAR(5),
	@DOTTHANHTOAN INT,
	@SOTIENTHANHTOAN FLOAT,
	@HANTHANHTOAN DATE,
	@DATHANHTOAN BIT
AS
BEGIN
	IF (@DOTTHANHTOAN = 4)
		BEGIN
			UPDATE HOADON
			SET DATHANHTOAN = @DATHANHTOAN
			WHERE HOADON.MA_HD = @MA_HD
		END

	UPDATE CHITIET_HD
	SET DATHANHTOAN = @DATHANHTOAN
	WHERE CHITIET_HD.MA_HD = @MA_HD

	UPDATE CHITIET_HD
	SET HANTHANHTOAN = @HANTHANHTOAN
	WHERE CHITIET_HD.MA_HD = @MA_HD
END
GO

