USE BENHVIENANHBINH
GO

CREATE PROC INSERT_PDKT
	@MA_PDKT CHAR(5),
	@MA_KH CHAR(5),
	@NGAYTIEM DATE,
	@MA_TT CHAR(5),
	@MA_GVX CHAR(5)
AS
BEGIN

	IF @NGAYTIEM <= (SELECT GETDATE())
		PRINT(N'Ngày tiêm không hợp lệ.')
	ELSE
		INSERT PHIEUDKTIEM VALUES(@MA_PDKT, @MA_KH, @MA_GVX, @MA_TT, @NGAYTIEM)
END
GO

EXEC INSERT_PDKT 'DK001', 'KH000', '2022-06-01', 'TT027', 'g0001'
DELETE PHIEUDKTIEM WHERE MA_PDKT = 'DK001'
SELECT*FROM GOIVACXIN


